# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('catalog', '0005_auto_20160611_1330'),
        ('users', '0002_ecuser_braintree_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('categories', models.ManyToManyField(blank=True, to='catalog.CatalogCategory')),
            ],
            bases=('auth.group',),
        ),
    ]
