# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('catalog', '0005_auto_20160611_1330'),
        ('users', '0004_auto_20160924_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_import', models.BooleanField(default=False)),
                ('is_export', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='catalog.CatalogCategory')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
