# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161012_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='auth.Group'),
        ),
    ]
