# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161021_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.Order')),
            ],
        ),
    ]
