# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='details',
            new_name='order',
        ),
    ]
