# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161024_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('delivered', 'delivered'), ('refunded', 'Refunded')], default='created', max_length=120),
        ),
    ]
