# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
