# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20161026_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
