# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20161026_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
