# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20161026_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='percentage',
            new_name='rate',
        ),
    ]
