# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20161026_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('$', 'USD')], default='$', max_length=120)),
            ],
        ),
    ]
