# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='ProductAttributeGroup',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
