# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='products.ProductAttributeValue', to='products.ProductAttribute'),
        ),
    ]
