# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='available_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
