# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160623_0645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttributeGroup',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='type',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
