# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160623_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
