# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160623_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_boolean',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_date',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_integer',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_text',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ProductAttribute'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute_value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.ProductAttribute'),
        ),
    ]
