# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20160623_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_allocated', models.IntegerField(verbose_name=0)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.ProductVariant')),
            ],
        ),
    ]
