# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
