# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20160625_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='variant',
        ),
    ]
