# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20160626_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.ProductVariant'),
        ),
    ]
