# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20160628_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
