# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productvariant_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price_override',
            new_name='price',
        ),
    ]
