# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import djecommerce.s3utils
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20160629_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, storage=djecommerce.s3utils.CustomS3BotoStorage(), upload_to=products.models.get_product_image_path),
        ),
    ]
