# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('tax_percentage', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
