# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
