# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20160703_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
